server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: changeit
    key-store-type: PKCS12
    key-alias: myalias

management:
  endpoints:
    web:
      exposure:
        include: "health, info, prometheus"

spring:
  application:
    name: https-gslb-api

security:
  user:
    name: admin
    password: 123
